### ISSUE TITLE
Make Wobserver usable as a standalone Plug

### ISSUE THREAD

**Issue by notriddle** [shinyscorpion/wobserver#1]
Instead of having wobserver run its own cowboy instance with (apparently) no authentication, I'd like to be able to run wobserver from inside an app's existing administrator panel.

The main barrier to this is wobserver's websockets, which can be replaced with [`EventSource`](https://developer.mozilla.org/en-US/docs/Web/API/EventSource).

**Comment by IanLuites** [comment]
Completely agree. We are currently running into the same thing. It is a waste to have multiple cowboy instances.

Completely dropping it would not be possible, because I would like to keep the drop-in usability.

I'm currently working on an option to just run it as plug without starting cowboy and when done will update the readme to show how to redirect the websocket.

Do note that the interface will fallback to the api/ajax if it can't connect through websocket.

**Comment by notriddle** [comment]
I'd like to have real-time updates, so forcing it to use fallback mode is kind of undesirable.

**Comment by IanLuites** [comment]
I think #2 should enable you to run wobserver as a plug.

Wobserver does not start a supervisor or `:cowboy` in `:plug` mode and I added an example in the config to show how to forward the requests and the websocket.

**Comment by IanLuites** [comment]
Version [0.1.4](https://hex.pm/packages/wobserver) is now on hex and has this feature.

**Comment by notriddle** [comment]
Cool, thanks.
