### ISSUE TITLE
No authorization test

### ISSUE THREAD

**Issue by OvermindDL1** [shinyscorpion/wobserver#21]
Currently we can put a plug in front of the router for wobserver to block access for an unauthorized user, but currently there is no way to do the same for the socket without hijacking between them.  The router should probably take a callback function that we can supply that gets passed the plug's conn and returns either a token (binary? easily generate-able securely via phoenix for example by the user) or an error.  If a token is returned then they are allowed to access the wobserver, if an error then it should just 404 or whatever.  The token should also be passed to the socket via the web page (or cookie) and the socket should verify that it is an allowed token (perhaps by passing it back to yet another user function, these could be specified in the config or on the injection sites), and if it is verified and allowed then the socket connection establishes else it is dropped.

Currently even if blocking the `/wobserver` route the outside can still access the websocket directly to query.

The most simple solution would probably just be adding 2 callback functions to the config, and if they exist use them, else allow all as it does now.

**Comment by IanLuites** [comment]
Issue has been fixed in release v0.1.7.

Security is now per default used as long as a `:security_key` is set in the config.

It is also possible to create a module that has the following methods:
   - `authenticate(Conn.t) :: Conn.t`
   - `authenticated?(Conn.t) :: boolean`
   - `authenticated?(:cowboy_req.req) :: boolean`

These will authenticate and check authentication on web connect and on socket connect. The custom module can be enabled by setting the `:security` config to the module name.
