### ISSUE TITLE
Is this project dead?- It is not, just completely rewritten

### ISSUE THREAD

**Issue by ghost** [shinyscorpion/wobserver#44]
I opened PR months ago, do you need some help? What can we do it keep it moving? Should we start forking and create a new hex  package?

**Comment by PhillippOhlandt** [comment]
Seems so. I wanted to offer my help for a better design but didn't get a response from one of the maintainers on twitter.

**Comment by KamilLelonek** [comment]
Too bad.

**Comment by ghost** [comment]
I have done a really simple fix regarding http(s) fallback a long ago.
@PhillippOhlandt @KamilLelonek  what do you think we should do. We can fork and get a new name for hex.pm.

**Comment by KamilLelonek** [comment]
On the one hand, it's a good idea, on the other, would someone maintain it afterwards?

**Comment by PhillippOhlandt** [comment]
That's a good question. I just wanted to start using it today (but can't due to version conflicts on httpoison with another lib). Not sure if I want to contribute to this project actively.

**Comment by KamilLelonek** [comment]
Exactly, and that's the problem.

**Comment by PhillippOhlandt** [comment]
Are you guys in the Elixir Slack channel?

**Comment by KamilLelonek** [comment]
I am.

**Comment by PhillippOhlandt** [comment]
I am `phillipp` there. Maybe we can create a private channel together with @steffenix to discuss what we could/want to do?

**Comment by KamilLelonek** [comment]
That's a good idea.

**Comment by PhillippOhlandt** [comment]
@KamilLelonek if you ping me on slack, I can invite you to the private channel I just created.

**Comment by IanLuites** [comment]
Hey, just to give you guys an update. The project is not dead, just in a state where a rewrite was definitely needed.

The rewrite has been in the works since before the Elixir conference, but with my limited time there has not been a release, yet. I've been lacks regarding back porting fixes, since I rather focus on getting the new release out.

I would strongly advise not to fork, but to start from scratch, which is pretty much what I did in my rewrite, because the current state is imho a *working* proof of concept, but not more than that.


Feel free to re-open if something is up, but to summarize:

- not dead, just being rewritten.
- low amount of fixes, because focus on completely different rewrite.
- advice: don't fork, start from scratch.

**Comment by PhillippOhlandt** [comment]
Hey, @IanLuites, thanks for the reply. I guess no one wants to start from scratch or even fork if this project is not dead. Maybe we can help you somehow?

**Comment by IanLuites** [comment]
The new version uses React to keep the interface part cleaner, but I would appreciate any input on design.

The original was pretty much copying `:observer` design, but there is no actual need for that. We can make it more web friendly.

The original was also my first experience with Elixir and I've learned so much. The code is going to be fine, especially with all the input on 0.1.x, I can make things work, but not make them pretty.

Help with code is harder, because the current 0.2 code base is pretty volatile.

**Comment by ghost** [comment]
Great to have news from you @IanLuites, if you need any help I would love to help even just testing and giving feedback if you feel code collaboration isn't possible now.

**Comment by steffkes** [comment]
@IanLuites any chance that you're publishing the current state of work, maybe just in a different branch? i'm not actually eager to use it like that, just so that people know where you're heading - instead of only looking at the current code. 

basically i'm just curious if there is any chance for me to contribute something :) running observer in containers is not really handy, so i was looking for alternatives and found wobserver .. and if possible, want help improving it further

**Comment by ghost** [comment]
Any news on the rewrite?

**Comment by stefmona** [comment]
Any news on the rewrite?
